### ISSUE TITLE
Value of the variable in AzDO Variable group is not chaged

### ISSUE THREAD

**Issue by kagarlickij** [microsoft/terraform-provider-azuredevops#240]
### Terraform (and Azure DevOps Provider) Version
Terraform v0.12.20
+ provider.azuredevops v0.0.1
+ provider.azurerm v2.0.0

### Terraform Configuration Files
```hcl
provider "azuredevops" {
    version = ">= 0.0.1"
    org_service_url = var.ados_url
    personal_access_token = var.ados_pat
}

provider "azurerm" {
    # version = "=2.0.0"
    features {}
}

resource "azuredevops_variable_group" "variablegroup" {
    project_id   = var.project_id
    name         = "Test Variable Group"
    description  = "Test Variable Group Description"
    allow_access = true

    variable {
        name  = "var1"
        value = "val1"
    }
}
```

### Expected Behavior

When I change value of the variable from `val1` to `val2` `terraform plan` must show the change and `terraform apply` must apply it

### Actual Behavior

`terraform plan` output: `No changes. Infrastructure is up-to-date.`

### Steps to Reproduce

1. `terraform apply`
2. Change value of the variable from `val1` to `val2`
3. `terraform plan`
4. `terraform apply`

**Comment by tmeckel** [comment]
@kagarlickij I was able to reproduce the error. Also, the implementation does not detect changes to the variable group in DevOps, not only in the `.tf` file. I'll have a closer look on this.

**Comment by tmeckel** [comment]
The problem lies inside the Terraform Plugin SDK, which does not perform a deep compare for the type 'set' when comparing values in a schema.

If the following is changed to `schema.TypeList` the bug is fixed.

https://github.com/microsoft/terraform-provider-azuredevops/blob/a6c79b5113a20b3430c74d5a8e71094c229fda0c/azuredevops/resource_variable_group.go#L56

Issue here is that, the user might now define multiple values for the same variable, which is indeed a misuse but should be handled via a proper error message inside the provider. The choice of `TypeSet` was unfortunately not optimal in this respect, because ultimately only the last defined value for a variable in the VariableGroup would have been set and there would have been no warning or error message.

**Comment by evertonmc** [comment]
I can also repro this. Just to be clear: tf plan/apply reacts to changes as soon as a `variable` set is added or removed to/from the group, but not when the `value` of an existing variable is changed.

**Comment by kevinhartman** [comment]
@tmeckel, is that a bug in the Terraform Plugin SDK, or documented behavior (that deep comparison is not used for sets)? Using a TypeList here doesn't seem quite right, since there are no ordering semantics for devops variables.

There *should* be a check somewhere to assert that multiple variables sharing the same name within the set results in an error. @awkwardindustries, any idea if/where that check exists?

**Comment by tmeckel** [comment]
@kevinhartman didn't have the time yet to check if this is really a bug inside the Terraform Plugin SDK or the behavior is by design.  But what we can do to circumvent the potential issue that the DevOps Api returns the variables in a different order than how they are stored in the state, is to sort the variables before we flatten them to the state.

Another benefit to use a `TypeList` would be to have a custom validation function. In contrast to the inline comments in the `schema.go` file 

![image](https://user-images.githubusercontent.com/14177833/75899556-fa154200-5e3b-11ea-9461-e27dd1c2e773.png)

the validation function is called for (at least) a `TypeList` member as well.

There is already a validation function inside the Plugin SDK, called `ListOfUniqueStrings` which leverages this support.

https://github.com/hashicorp/terraform-plugin-sdk/blob/0150ffa9c963510f4c10aa672a4e345022d92fba/helper/validation/list.go#L17

The (custom) validation function could check if the user defined multiple variables with the same name and issue an error in that case.

**Comment by nmiodice** [comment]
Seems as though there is logic elsewhere in the SDK plugin that prevents such as solution (at this time).

Based on the following change:
```go
			"variable": {
				Type: schema.TypeList,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:     schema.TypeString,
							Required: true,
						},
						"value": {
							Type:     schema.TypeString,
							Optional: true,
							Default:  "",
						},
						"is_secret": {
							Type:     schema.TypeBool,
							Optional: true,
							Default:  false,
						},
					},
				},
				ValidateFunc: validate.ListOfMapsHasNoDuplicateKeys("name"),
				Required:     true,
				MinItems:     1,
```

I still get this locally:
```bash
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
        * resource azuredevops_variable_group: variable: ValidateFunc is not yet supported on lists or sets.
```

**Comment by nmiodice** [comment]
Non optimal fix, based on my findings trying to do it the right way (and not succeeding) - can be found here https://github.com/microsoft/terraform-provider-azuredevops/pull/254

I appreciate feedback on it :)

**Comment by tmeckel** [comment]
The `ListOfUniqueStrings` method that I mentioned in my comment above is part of the Terraform Plugin SDK since [1.6.0](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/CHANGELOG.md#160-january-29-2020) so and there's also a unit test for this method (https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/validation/list_test.go). Perhaps there's still something wrong with the plumbing inside the schema functions which implement (call) the defined validation functions. I'll have a closer look on this if I find some time during the work week.

Oh and about the implementation of your validation function `` I'd use Go Linq and [grouping](https://pkg.go.dev/github.com/ahmetb/go-linq?tab=doc#Query.GroupBy) the elements of the list by their keys and then filter on groups with a member count greater than 1 and emit an error if the returned collection contains any elements. Same strategy as would implement this in C#.  I'd think this would generate much less and more readable code.

**Comment by nmiodice** [comment]
Fixed in https://github.com/microsoft/terraform-provider-azuredevops/pull/254

@tmeckel I was unable to get this working with the validation capabilities of the TF development SDK, based on my error logs above, even after updating the SDK to the latest version.

Happy to circle back when that limitation no longer exists.
