### ISSUE TITLE
azuredevops provider causes error="exit status 2" when run in pipeline

### ISSUE THREAD

**Issue by raphaelschnaitl** [microsoft/terraform-provider-azuredevops#26]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_serviceendpoint_azurerm`

### Debug Output

```
2020-07-02T09:53:27.2589997Z 2020/07/02 09:53:27 [TRACE] GRPCProvider: ReadResource
2020-07-02T09:53:27.2590805Z azuread_group_member.service_principal_tf_access["numanagement"]: Refreshing state... [id=2200fae0-70c8-41ca-90dd-dbd2aefe1b75/member/30c2715a-9afa-4fd3-a439-a98265219c96]
2020-07-02T09:53:27.2592201Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: User-Agent: Go/go1.14.2 (amd64-linux) go-autorest/v14.0.0 Azure-SDK-For-Go/v42.1.0 graphrbac/1.6 HashiCorp Terraform/0.12.28 (+https://www.terraform.io) Terraform Plugin SDK/1.6.0 terraform-provider-azuread/0.10.0 VSTS_f9ed5db8-47f3-4826-8a51-a7e7064eb962_Release__45_83_2
2020-07-02T09:53:27.2593347Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: Accept-Encoding: gzip
2020-07-02T09:53:27.2593974Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: 
2020-07-02T09:53:27.2594577Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: 
2020-07-02T09:53:27.2595283Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: 2020/07/02 09:53:27 [DEBUG] AzureAD Request: 
2020-07-02T09:53:27.2596462Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: GET /***/groups/2200fae0-70c8-41ca-90dd-dbd2aefe1b75/members?api-version=1.6 HTTP/1.1
2020-07-02T09:53:27.2597449Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: Host: graph.windows.net
2020-07-02T09:53:27.2598733Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: User-Agent: Go/go1.14.2 (amd64-linux) go-autorest/v14.0.0 Azure-SDK-For-Go/v42.1.0 graphrbac/1.6 HashiCorp Terraform/0.12.28 (+https://www.terraform.io) Terraform Plugin SDK/1.6.0 terraform-provider-azuread/0.10.0 VSTS_f9ed5db8-47f3-4826-8a51-a7e7064eb962_Release__45_83_2
2020-07-02T09:53:27.2599806Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: Accept-Encoding: gzip
2020-07-02T09:53:27.2600446Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: 
2020-07-02T09:53:27.2601032Z 2020-07-02T09:53:27.254Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: 
2020-07-02T09:53:27.2835364Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: azuread_group_member.service_principal_tf_access["leistungsmeldung"]: Refreshing state... [id=db5c0559-eaf7-4ef3-99d5-495bd26ae84e/member/a22f874c-ad08-47ad-a907-e23202ed71bc]
2020-07-02T09:53:27.3010318Z azuread_group_member.service_principal_contributor["leistungsmeldung"]: Refreshing state... [id=628d9e69-ae5f-4add-ada7-c822434d5060/member/a22f874c-ad08-47ad-a907-e23202ed71bc]
2020-07-02T09:53:27.3093957Z azuread_group_member.service_principal_contributor["mobilelv"]: Refreshing state... [id=ca46878e-d0bb-44e5-8cd2-e69a15a26773/member/b283e5f8-13e8-4058-b9df-ec57aa43a7be]
2020-07-02T09:53:27.3411143Z azuread_group_member.service_principal_contributor["numanagement"]: Refreshing state... [id=96775237-7946-42ce-b214-b47fbc49a4ad/member/30c2715a-9afa-4fd3-a439-a98265219c96]
2020-07-02T09:53:27.3496538Z azuread_group_member.service_principal_contributor["bidderoffer"]: Refreshing state... [id=d4b46ea4-f1f0-4136-b162-d7f83094c067/member/e75073c6-7641-4a8c-a7ea-f346fe9fd571]
2020-07-02T09:53:27.3563653Z azuread_group_member.service_principal_contributor["businessintelligence"]: Refreshing state... [id=a394c0cf-97d1-40d3-8b1a-209bb1935fc1/member/1b7cef24-175c-4a06-a11c-e2c3b2bc3fcd]
2020-07-02T09:53:27.7013331Z panic: runtime error: invalid memory address or nil pointer dereference
2020-07-02T09:53:27.7014718Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe4e6a9]
2020-07-02T09:53:27.7015595Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 
2020-07-02T09:53:27.7016375Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: goroutine 55 [running]:
2020-07-02T09:53:27.7017595Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.doBaseFlattening(0xc0001a6930, 0xc0004f1c80, 0xc00056d0b0)
2020-07-02T09:53:27.7019057Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:88 +0x179
2020-07-02T09:53:27.7020521Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.flattenServiceEndpointAzureRM(0xc0001a6930, 0xc0004f1c80, 0xc00056d0b0)
2020-07-02T09:53:27.7022346Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm.go:127 +0x5a
2020-07-02T09:53:27.7023939Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointReadFunc.func1(0xc0001a6930, 0xee91e0, 0xc000296240, 0xc0001a6930, 0x0)
2020-07-02T09:53:27.7025458Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:209 +0x4af
2020-07-02T09:53:27.7026931Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000109800, 0xc0004c9450, 0xee91e0, 0xc000296240, 0xc00000e848, 0x0, 0x0)
2020-07-02T09:53:27.7028680Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-07-02T09:53:27.7030238Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000a6b38, 0x137d860, 0xc000581350, 0xc0004c9270, 0xc0000a6b38, 0xc000581350, 0xc0001dba48)
2020-07-02T09:53:27.7031949Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-07-02T09:53:27.7033582Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x10c2d20, 0xc0000a6b38, 0x137d860, 0xc000581350, 0xc000540960, 0x0, 0x137d860, 0xc000581350, 0xc00033af00, 0x26d)
2020-07-02T09:53:27.7035155Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
2020-07-02T09:53:27.7036599Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d6000, 0x138ab80, 0xc0000abe00, 0xc00032f400, 0xc000122120, 0x1af81d0, 0x0, 0x0, 0x0)
2020-07-02T09:53:27.7037965Z 2020-07-02T09:53:27.280Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-07-02T09:53:27.7039198Z 2020-07-02T09:53:27.281Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000d6000, 0x138ab80, 0xc0000abe00, 0xc00032f400, 0x0)
2020-07-02T09:53:27.7040500Z 2020-07-02T09:53:27.281Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
2020-07-02T09:53:27.7041802Z 2020-07-02T09:53:27.281Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000428010, 0xc0000d6000, 0x138ab80, 0xc0000abe00, 0xc00032f400)
2020-07-02T09:53:27.7043195Z 2020-07-02T09:53:27.281Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:710 +0xa1
2020-07-02T09:53:27.7044322Z 2020-07-02T09:53:27.281Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-07-02T09:53:27.7045534Z 2020-07-02T09:53:27.281Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-07-02T09:53:27.7046838Z 2020-07-02T09:53:27.281Z [DEBUG] plugin: plugin process exited: path=/home/vsts/work/r1/a/IaC/TerraformBundle/.terraform/plugins/linux_amd64/terraform-provider-azuredevops_v0.0.1_x4 pid=3024 error="exit status 2"
2020-07-02T09:53:27.7047623Z 2020/07/02 09:53:27 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020-07-02T09:53:27.7048280Z 2020/07/02 09:53:27 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020-07-02T09:53:27.7048923Z 2020/07/02 09:53:27 [TRACE] [walkRefresh] Exiting eval tree: azuredevops_serviceendpoint_azurerm.service_principals["businessintelligence"]
2020-07-02T09:53:27.7049617Z 2020/07/02 09:53:27 [TRACE] vertex "azuredevops_serviceendpoint_azurerm.service_principals[\"businessintelligence\"]": visit complete
2020-07-02T09:53:27.7050172Z 2020/07/02 09:53:27 [TRACE] <root>: eval: *terraform.EvalSequence
2020-07-02T09:53:27.7050564Z 2020/07/02 09:53:27 [TRACE] <root>: eval: *terraform.EvalGetProvider
2020-07-02T09:53:27.7050971Z 2020/07/02 09:53:27 [TRACE] <root>: eval: *terraform.EvalReadState
2020-07-02T09:53:27.7051526Z 2020/07/02 09:53:27 [TRACE] EvalReadState: reading state for azuread_group_member.service_principal_tf_access["leistungsmeldung"]
2020-07-02T09:53:27.7052675Z 2020/07/02 09:53:27 [TRACE] UpgradeResourceState: schema version of azuread_group_member.service_principal_tf_access["leistungsmeldung"] is still 0; calling provider "registry.terraform.io/-/azuread" for any other minor fixups
2020-07-02T09:53:27.7053338Z 2020/07/02 09:53:27 [TRACE] GRPCProvider: UpgradeResourceState
2020-07-02T09:53:27.7053751Z 2020/07/02 09:53:27 [TRACE] <root>: eval: *terraform.EvalRefreshDependencies
2020-07-02T09:53:27.7054154Z 2020/07/02 09:53:27 [TRACE] <root>: eval: *terraform.EvalRefresh
2020-07-02T09:53:27.7054532Z 2020/07/02 09:53:27 [TRACE] GRPCProvider: ReadResource
```

### Expected Behavior

terraform apply should work in pipeline aswell.

### Actual Behavior

terraform fails when run in pipeline

### Steps to Reproduce

* Create a Azure DevOps Pipeline that "Builds" terraform:
```
terraform init -backend=false -input=false
terraform validate
```
* Pack the Build into an Artefact in Azure DevOps
* Create a realease pipeline that "Deploys" the Artefact:

```
cd ./IaC/TerraformBundle
chmod +x ./.terraform/plugins/*/*
terraform init -get-plugins=false -get=false -no-color
terraform workspace select testing -no-color
terraform apply -auto-approve -input=false -no-color
```

The Release Pipeline fails when running terraform apply.

### Important Factoids

I did not immediately see the panic: runtime error and created a SO question [here](https://stackoverflow.com/questions/62693906/terraform-causes-rpc-error-when-run-from-pipeline). It also contains some more context.

**Comment by xuzhang3** [comment]
Hi @Console32  Thanks for opening this issue. I have create a PR fix this issue #60 . Before the new version released. A workaround for this issue is not to set the service connections description to an empty string .

**Comment by raphaelschnaitl** [comment]
Thanks @xuzhang3 !

Sorry to bother you, Where (on which ressource) should i set a description as workaround?

**Comment by xuzhang3** [comment]
@Console32 Your .tf configure file. `azuredevops_serviceendpoint_azurerm.description`

![image](https://user-images.githubusercontent.com/57888764/86740958-9dd06200-c069-11ea-8ce8-e912b587bd79.png)

**Comment by raphaelschnaitl** [comment]
Ah okay, will check asap. The `description` property is missing from the [documentation](https://www.terraform.io/docs/providers/azuredevops/r/serviceendpoint_azurerm.html), can you. add it there aswell?

**Comment by xuzhang3** [comment]
If you not configure the description in your .tf file,  description will be set to 'Managed by Terraform' by default.  Have you changed the description through portal UI?
I will update the document.

**Comment by raphaelschnaitl** [comment]
I have not changed the description, I just checked in the portal. All service connections now have my description set. I do still get the following error:

```
2020-07-07T08:29:17.4706738Z 2020-07-07T08:29:17.366Z [DEBUG] plugin.terraform-provider-azuread_v0.10.0_x4: {"odata.metadata":"https://graph.windows.net/***/$metadata#directoryObjects","value":[{"odata.type":"Microsoft.DirectoryServices.User","objectType":"User","objectId":"be7dacc7-2eda-45d4-80e7-2538c5723000","deletionTimestamp":null,"accountEnabled":true,"ageGroup":null,"assignedLicenses":[],"assignedPlans":[],"city":null,"companyName":null,"consentProvidedForMinor":null,"country":null,"createdDateTime":"2020-02-11T07:48:49Z","creationType":"Invitation","department":null,"dirSyncEnabled":null,"displayName":"Eugen Scherbin","employeeId":null,"facsimileTelephoneNumber":null,"givenName":null,"immutableId":null,"isCompromised":null,"jobTitle":null,"lastDirSyncTime":null,"legalAgeGroupClassification":null,"mail":"eugen.scherbin@brz.eu","mailNickname":"eugen.scherbin_brz.eu#EXT#","mobile":null,"onPremisesDistinguishedName":null,"onPremisesSecurityIdentifier":null,"otherMails":["eugen.scherbin@brz.eu"],"passwordPolicies":null,"passwordProfile":null,"physicalDeliveryOfficeName":null,"postalCode":null,"preferredLanguage":null,"provisionedPlans":[],"provisioningErrors":[],"proxyAddresses":["SMTP:eugen.scherbin@brz.eu"],"refreshTokensValidFromDateTime":"2020-02-11T07:48:49Z","showInAddressList":false,"signInNames":[],"sipProxyAddress":null,"state":null,"streetAddress":null,"surname":null,"telephoneNumber":null,"thumbnailPhoto@odata.mediaEditLink":"directoryObjects/be7dacc7-2eda-45d4-80e7-2538c5723000/Microsoft.DirectoryServices.User/thumbnailPhoto","usageLocation":null,"userIdentities":[],"userPrincipalName":"eugen.scherbin_brz.eu#EXT#@brz365.onmicrosoft.com","userState":"Accepted","userStateChangedOn":"2020-02-11T07:51:01Z","userType":"Guest"},{"odata.type":"Microsoft.DirectoryServices.User","objectType":"User","objectId":"5b72f31a-1e49-407e-a3da-7e0d16b30957","deletionTimestamp":null,"accountEnabled":true,"ageGroup":null,"assignedLicenses":[],"assignedPlans":[],"city":null,"companyName":null,"consentProvidedForMinor":null,"country":null,"createdDateTime":"2020-04-03T08:18:56Z","creationType":"Invitation","department":null,"dirSyncEnabled":null,"displayName":"Alexandra Shulenina","employeeId":null,"facsimileTelephoneNumber":null,"givenName":null,"immutableId":null,"isCompromised":null,"jobTitle":null,"lastDirSyncTime":null,"legalAgeGroupClassification":null,"mail":"alexandra.shulenina@brz.eu","mailNickname":"alexandra.shulenina_brz.eu#EXT#","mobile":null,"onPremisesDistinguishedName":null,"onPremisesSecurityIdentifier":null,"otherMails":["alexandra.shulenina@brz.eu"],"passwordPolicies":null,"passwordProfile":null,"physicalDeliveryOfficeName":null,"postalCode":null,"preferredLanguage":null,"provisionedPlans":[],"provisioningErrors":[],"proxyAddresses":["SMTP:alexandra.shulenina@brz.eu"],"refreshTokensValidFromDateTime":"2020-04-03T08:18:56Z","showInAddressList":false,"signInNames":[],"sipProxyAddress":null,"state":null,"streetAddress":null,"surname":null,"telephoneNumber":null,"thumbnailPhoto@odata.mediaEditLink":"directoryObjects/5b72f31a-1e49-407e-a3da-7e0d16b30957/Microsoft.DirectoryServices.User/thumbnailPhoto","usageLocation":null,"userIdentities":[],"userPrincipalName":"alexandra.shulenina_brz.eu#EXT#@brz365.onmicrosoft.com","userState":"Accepted","userStateChangedOn":"2020-04-06T09:23:00Z","userType":"Guest"},{"odata.type":"Microsoft.DirectoryServices.User","objectType":"User","objectId":"7f3f0a54-5b4e-4e05-9bd3-f6b3eee01935","deletionTimestamp":null,"accountEnabled":true,"ageGroup":null,"assignedLicenses":[],"assignedPlans":[],"city":null,"companyName":null,"consentProvidedForMinor":null,"country":null,"createdDateTime":"2020-04-03T08:22:16Z","creationType":"Invitation","department":null,"dirSyncEnabled":null,"displayName":"Christian Kr\u00e4utner","employeeId":null,"facsimileTelephoneNumber":null,"givenName":null,"immutableId":null,"isCompromised":null,"jobTitle":null,"lastDirSyncTime":null,"legalAgeGroupClassification":null,"mail":"christian.kraeutner@brz.eu","mailNickname":"christian.kraeutner_brz.eu#EXT#","mobile":null,"onPremisesDistinguishedName":null,"onPremisesSecurityIdentifier":null,"otherMails":["christian.kraeutner@brz.eu"],"passwordPolicies":null,"passwordProfile":null,"physicalDeliveryOfficeName":null,"postalCode":null,"preferredLanguage":null,"provisionedPlans":[],"provisioningErrors":[],"proxyAddresses":["SMTP:christian.kraeutner@brz.eu"],"refreshTokensValidFromDateTime":"2020-04-03T08:22:16Z","showInAddressList":false,"signInNames":[],"sipProxyAddress":null,"state":null,"streetAddress":null,"surname":null,"telephoneNumber":null,"thumbnailPhoto@odata.mediaEditLink":"directoryObjects/7f3f0a54-5b4e-4e05-9bd3-f6b3eee01935/Microsoft.DirectoryServices.User/thumbnailPhoto","usageLocation":null,"userIdentities":[],"userPrincipalName":"christian.kraeutner_brz.eu#EXT#@brz365.onmicrosoft.com","userState":"Accepted","userStateChangedOn":"2020-04-03T08:23:45Z","userType":"Guest"},{"odata.type":"Microsoft.DirectoryServices.User","objectType":"User","objectId":"55dd0ee8-957a-41cf-94ef-b728aca6adbe","deletionTimestamp":null,"accountEnabled":true,"ageGroup":null,"assignedLicenses":[],"assignedPlans":[],"city":null,"companyName":null,"consentProvidedForMinor":null,"country":null,"createdDateTime":"2020-04-06T09:08:34Z","creationType":"Invitation","department":null,"dirSyncEnabled":null,"displayName":"Tobias Wismet","employeeId":null,"facsimileTelephoneNumber":null,"givenName":"Tobias","immutableId":null,"isCompromised":null,"jobTitle":null,"lastDirSyncTime":null,"legalAgeGroupClassification":null,"mail":"tobias.wismet@brz.eu","mailNickname":"tobias.wismet_brz.eu#EXT#","mobile":null,"onPremisesDistinguishedName":null,"onPremisesSecurityIdentifier":null,"otherMails":["tobias.wismet@brz.eu"],"passwordPolicies":null,"passwordProfile":null,"physicalDeliveryOfficeName":null,"postalCode":null,"preferredLanguage":null,"provisionedPlans":[],"provisioningErrors":[],"proxyAddresses":["SMTP:tobias.wismet@brz.eu"],"refreshTokensValidFromDateTime":"2020-04-06T09:08:33Z","showInAddressList":false,"signInNames":[],"sipProxyAddress":null,"state":null,"streetAddress":null,"surname":"Wismet","telephoneNumber":null,"thumbnailPhoto@odata.mediaEditLink":"directoryObjects/55dd0ee8-957a-41cf-94ef-b728aca6adbe/Microsoft.DirectoryServices.User/thumbnailPhoto","usageLocation":null,"userIdentities":[],"userPrincipalName":"tobias.wismet_brz.eu#EXT#@brz365.onmicrosoft.com","userState":"Accepted","userStateChangedOn":"2020-04-06T09:10:17Z","userType":"Guest"},{"odata.type":"Microsoft.DirectoryServices.ServicePrincipal","objectType":"ServicePrincipal","objectId":"1b7cef24-175c-4a06-a11c-e2c3b2bc3fcd","deletionTimestamp":null,"accountEnabled":true,"addIns":[],"alternativeNames":[],"appDisplayName":"BRZ365BusinessintelligenceTestingServicePrincipal","appId":"79c52445-b99e-4b71-bf78-e98883d5e90f","applicationTemplateId":null,"appOwnerTenantId":"***","appRoleAssignmentRequired":false,"appRoles":[],"displayName":"BRZ365BusinessintelligenceTestingServicePrincipal","errorUrl":null,"homepage":"https://BRZ365BusinessintelligenceTestingServicePrincipal","informationalUrls":{"termsOfService":null,"support":null,"privacy":null,"marketing":null},"keyCredentials":[],"logoutUrl":null,"notificationEmailAddresses":[],"oauth2Permissions":[{"adminConsentDescription":"Allow the application to access BRZ365BusinessintelligenceTestingServicePrincipal on behalf of the signed-in user.","adminConsentDisplayName":"Access BRZ365BusinessintelligenceTestingServicePrincipal","id":"6cc629f8-adfc-4908-9dd8-e38508bc8360","isEnabled":true,"type":"User","userConsentDescription":"Allow the application to access BRZ365BusinessintelligenceTestingServicePrincipal on your behalf.","userConsentDisplayName":"Access BRZ365BusinessintelligenceTestingServicePrincipal","value":"user_impersonation"}],"passwordCredentials":[],"preferredSingleSignOnMode":null,"preferredTokenSigningKeyEndDateTime":null,"preferredTokenSigningKeyThumbprint":null,"publisherName":"BRZ365 SharedServices","replyUrls":[],"samlMetadataUrl":null,"samlSingleSignOnSettings":null,"servicePrincipalNames":["79c52445-b99e-4b71-bf78-e98883d5e90f"],"servicePrincipalType":"Application","signInAudience":"AzureADMyOrg","tags":[],"tokenEncryptionKeyId":null}]}
2020-07-07T08:29:17.9073969Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: panic: runtime error: invalid memory address or nil pointer dereference
2020-07-07T08:29:17.9075321Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe4e6a9]
2020-07-07T08:29:17.9076105Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 
2020-07-07T08:29:17.9076798Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: goroutine 60 [running]:
2020-07-07T08:29:17.9079452Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.doBaseFlattening(0xc00011ec40, 0xc000118780, 0xc0001dbf40)
2020-07-07T08:29:17.9081678Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:88 +0x179
2020-07-07T08:29:17.9083523Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.flattenServiceEndpointAzureRM(0xc00011ec40, 0xc000118780, 0xc0001dbf40)
2020-07-07T08:29:17.9085779Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_azurerm.go:127 +0x5a
2020-07-07T08:29:17.9088829Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint.genServiceEndpointReadFunc.func1(0xc00011ec40, 0xee91e0, 0xc00029e240, 0xc00011ec40, 0x0)
2020-07-07T08:29:17.9090364Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/azuredevops/internal/service/serviceendpoint/commons.go:209 +0x4af
2020-07-07T08:29:17.9092418Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000119800, 0xc0005f6320, 0xee91e0, 0xc00029e240, 0xc00000e230, 0x0, 0x0)
2020-07-07T08:29:17.9093832Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-07-07T08:29:17.9096525Z 2020-07-07T08:29:17.367Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0000bcb38, 0x137d860, 0xc0006121e0, 0xc0005f60f0, 0xc0000bcb38, 0xc0006121e0, 0xc000554a48)
2020-07-07T08:29:17.9098744Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-07-07T08:29:17.9100446Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x10c2d20, 0xc0000bcb38, 0x137d860, 0xc0006121e0, 0xc0005fa0c0, 0x0, 0x137d860, 0xc0006121e0, 0xc00068e000, 0x2be)
2020-07-07T08:29:17.9102122Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
2020-07-07T08:29:17.9103570Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e6000, 0x138ab80, 0xc000001e00, 0xc00010e000, 0xc000374cc0, 0x1af81d0, 0x0, 0x0, 0x0)
2020-07-07T08:29:17.9104697Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-07-07T08:29:17.9105759Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000e6000, 0x138ab80, 0xc000001e00, 0xc00010e000, 0x0)
2020-07-07T08:29:17.9107091Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
2020-07-07T08:29:17.9108373Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000b8370, 0xc0000e6000, 0x138ab80, 0xc000001e00, 0xc00010e000)
2020-07-07T08:29:17.9109559Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:710 +0xa1
2020-07-07T08:29:17.9110664Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-07-07T08:29:17.9111906Z 2020-07-07T08:29:17.368Z [DEBUG] plugin.terraform-provider-azuredevops_v0.0.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azuredevops/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-07-07T08:29:17.9112671Z 2020/07/07 08:29:17 [ERROR] <root>: eval: *terraform.EvalReadState, err: rpc error: code = Unavailable desc = transport is closing
```

Could it be that there is something else missing, and the API is not returning a description?

**Comment by xuzhang3** [comment]
@Console32  Can you provide your .tf configure? Be sure the sensitive data has been masked. 
If the description not set,  API will return description as `null` which will cause this issue.

**Comment by raphaelschnaitl** [comment]
The resource is defined as following:
```
resource "azuredevops_serviceendpoint_azurerm" "service_principals" {
  for_each              = {for k, v in var.backends: k => v if v.azure_devops_project != null}
  project_id            = data.azuredevops_project.devops_project[each.key].id
  service_endpoint_name = "azurerm-${each.value.application}-${local.settings.environment}"
  description           = "ServiceConnection for Service \"${each.value.application}\" and Environment \"${local.settings.environment}\""

  credentials {
    serviceprincipalid  = module.service_principals.aad_service_principals[each.key].application_id
    serviceprincipalkey = module.service_principals.service_principal_secrets[each.key]
  }

  azurerm_spn_tenantid      = data.azurerm_subscription.subscription.tenant_id
  azurerm_subscription_id   = data.azurerm_subscription.subscription.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.subscription.display_name
}
```

I applied everything on my local machine (this works as expected)
tf plan and tf apply fail on the build agent.

the state (`terraform show | grep description`) is:
```
    description               = "ServiceConnection for Service \"...\" and Environment \"testing\""
    description               = "ServiceConnection for Service \"...\" and Environment \"testing\""
    description               = "ServiceConnection for Service \"...\" and Environment \"testing\""
    description               = "ServiceConnection for Service \"...\" and Environment \"testing\""
    description               = "ServiceConnection for Service \"...\" and Environment \"testing\""
```

**Comment by xuzhang3** [comment]
@Console32 I need check this issue in pipeline environment.
Can you use the following configuration to check the actual executed .tf script?
```
output "azurerm_service_connection" {
  value = azuredevops_serviceendpoint_azurerm.endpointazure
}
```

**Comment by raphaelschnaitl** [comment]
The output for all 5 of my service connections look like this: 
```hcl
azurerm_service_connection = {
  "..." = {
    "authorization" = {
      "scheme" = "ServicePrincipal"
    }
    "azurerm_spn_tenantid" = "value_omitted"
    "azurerm_subscription_id" = "value_omitted"
    "azurerm_subscription_name" = "shared-...-001"
    "credentials" = [
      {
        "serviceprincipalid" = "value_omitted"
        "serviceprincipalkey" = ""
        "serviceprincipalkey_hash" = "value_omitted"
      },
    ]
    "description" = "ServiceConnection for Service \"...\" and Environment \"testing\""
    "id" = "value_omitted"
    "project_id" = "value_omitted"
    "service_endpoint_name" = "azurerm-...-testing"
}
```

Now I have some more troubling issues. It looks like my change to the description of the `azuredevops_serviceendpoint_azurerm` caused terraform to drop the serviceprincipalkey 

Since I changed the `description` all service connections report errors:

```
AADSTS7000215: Invalid client secret is provided. Trace ID: 40f069d5-e6b9-4377-b11b-52698a097900 Correlation ID: 4060270d-54c3-445d-8f86-c5ebf5b5bf77 Timestamp: 2020-07-07 09:52:32Z
```

I had to manually enter them again using the UI. Should I create a new Issue for this?

**Comment by xuzhang3** [comment]
This error message `AADSTS7000215: Invalid client secret is provided. Trace ID: 40f069d5-e6b9-4377-b11b-52698a097900 Correlation ID: 4060270d-54c3-445d-8f86-c5ebf5b5bf77 Timestamp: 2020-07-07 09:52:32Z`   looks like that you script is parsed in the wrong format.  Maybe  `\"` or `\` cause unwanted string parse issue, I'm not sure.

Two way to solve your problem:
1. waiting our next release
2. package the provider plugin yourself(be sure you have golang environment)
  - check out branch #60 
  - open your cmd/terminal and go to source code root folder
  - use command `go build -gcflags="-N -l" -o terraform-provider-azuredevops`. If you use Terraform in windows, use `go build -gcflags="-N -l" -o terraform-provider-azuredevops.exe`
  - use the provider you just packaged to provision Azure Devops resources.


@Console32  I cannot reproduce your error. 
I test three .tf script in pipeline environment.
### set `description=""`    **failed**
```
resource "azuredevops_project" "project" {
  project_name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "TestServiceRM"
  description = ""
  credentials {
    serviceprincipalid  = "xxx"
    serviceprincipalkey = "xxx"
  }
  azurerm_spn_tenantid      = "xxx"
  azurerm_subscription_id   = "xxx"
  azurerm_subscription_name = "Sample AzureRM Subscription"
}

output "azurerm_service_connection" {
  value = azuredevops_serviceendpoint_azurerm.endpointazure
}
```

### set `description="test"`  **success**
```
resource "azuredevops_project" "project" {
  project_name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "TestServiceRM"
  description = "test"
  credentials {
    serviceprincipalid  = "xxx"
    serviceprincipalkey = "xxx"
  }
  azurerm_spn_tenantid      = "xxx"
  azurerm_subscription_id   = "xxx"
  azurerm_subscription_name = "Sample AzureRM Subscription"
}

output "azurerm_service_connection" {
  value = azuredevops_serviceendpoint_azurerm.endpointazure
}
```

### set `description="ServiceConnection for Service \"...\" and Environment \"testing\""`    **success**
```
resource "azuredevops_project" "project" {
  project_name       = "Sample Project"
  visibility         = "private"
  version_control    = "Git"
  work_item_template = "Agile"
}

resource "azuredevops_serviceendpoint_azurerm" "endpointazure" {
  project_id            = azuredevops_project.project.id
  service_endpoint_name = "TestServiceRM"
  description = "ServiceConnection for Service \"...\" and Environment \"testing\""
  credentials {
    serviceprincipalid  = "xxx"
    serviceprincipalkey = "xxx"
  }
  azurerm_spn_tenantid      = "xxx"
  azurerm_subscription_id   = "xxx"
  azurerm_subscription_name = "Sample AzureRM Subscription"
}

output "azurerm_service_connection" {
  value = azuredevops_serviceendpoint_azurerm.endpointazure
}
```

**Comment by raphaelschnaitl** [comment]
Regarding the nil exception inside pipeline: Thanks for your effort, I will wait for the new version of the Provider (can your provider a rough estimate how long this will take (is it weeks, or months?)

Regarding the lost secrets: I can reproduce this doing the following:

1) I deploy a working service principal using terraform
2) navigate to the AzureDevops UI -> Project Settings -> Service Connections -> "azurerm-testing" -> Edit
3) Validate that the service connection works using the `Verify and save` Button. 
4) Close the Edit dialog
5) Deploy the following Change

```hcl
# azuredevops_serviceendpoint_azurerm.service_principals["leistungsmeldung"] will be updated in-place
  ~ resource "azuredevops_serviceendpoint_azurerm" "service_principals" {
        authorization             = {
            "scheme" = "ServicePrincipal"
        }
        azurerm_spn_tenantid      = "..."
        azurerm_subscription_id   = "...."
        azurerm_subscription_name = "shared-testing-001"
      ~ description               = "Managed by Terraform" -> "TestDescription"
        id                        = "...."
        project_id                = "...."
        service_endpoint_name     = "azurerm-testing"

        credentials {
            serviceprincipalid       = "..."
            serviceprincipalkey_hash = (sensitive value)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

6) Validate Again -> it no longer is working and shows the following Error.

<img width="516" alt="Screenshot 2020-07-07 at 13 46 06" src="https://user-images.githubusercontent.com/4870099/86777355-53df8000-c059-11ea-9cf3-a93aceab6697.png">

**Comment by xuzhang3** [comment]
@Console32  Thanks for  your feedback. Follow your operation steps, I cannot reproduce error. Did you change any configurations in  step 2?   It is  recommend  not to use Terraform and UI web at the same time. this may cause unexpected error.

**Comment by xuzhang3** [comment]
I cannot give you a timeline, it may take two or three week before our next release. This Terraform provider just released the v0.0.1 and we have a lot works to do, new features, bug fix, enhancement etc.

**Comment by raphaelschnaitl** [comment]
@xuzhang3 Thanks for the estimation. No I did not change anything in the UI. Just the Steps that I outlined here.
If I have time today I will create a small reproduction example so I can share the complete code with you.

**Comment by xuzhang3** [comment]
Closing this issue. Issue is fixed in #60

**Comment by raphaelschnaitl** [comment]
@xuzhang3 I Today had the same error on my lokal machine. We did not change any of the terraform, just extended the collection by one new `backend`. In fact, a cowerker of mine did add this 'backend' which uses another Azure DevOps Project.

Can reproduce the error by creating a service connection as Project Admin, and downgrading the user to just Project Reader. After this steps terraform plan fails with a panic, instead of a AccessDenied error.

**Comment by xuzhang3** [comment]
@Console32  The new version has not been released.

**Comment by xuzhang3** [comment]
@Console32 Can I see your .tf configs? Please mask the sensitive data.

**Comment by raphaelschnaitl** [comment]
The terraform is still the same.

terraform.tf 
```
provider "azuredevops" {
  org_service_url = "https://dev.azure.com/....."
}
```

service_connections.tf
```
data "azuredevops_project" "devops_project" {
  for_each     = var.backends
  project_name = each.value.azure_devops_project
}

resource "azuredevops_serviceendpoint_azurerm" "service_principals" {
  for_each              = {for k, v in var.backends: k => v if v.azure_devops_project != null}
  project_id            = data.azuredevops_project.devops_project[each.key].id
  service_endpoint_name = "azurerm-${each.value.application}-${local.settings.environment}"

  credentials {
    serviceprincipalid  = module.service_principals.aad_service_principals[each.key].application_id
    serviceprincipalkey = module.service_principals.service_principal_secrets[each.key]
  }

  azurerm_spn_tenantid      = data.azurerm_subscription.subscription.tenant_id
  azurerm_subscription_id   = data.azurerm_subscription.subscription.subscription_id
  azurerm_subscription_name = data.azurerm_subscription.subscription.display_name
}
```

As I already mentioned. The `tf plan` works when I am Part of the `Endpoint Administrators` Group in Azure DevOps:
![image](https://user-images.githubusercontent.com/4870099/87646144-b407ad80-c74e-11ea-8a82-9065dfdb23db.png)

But fails when I am only `Project Reader` (which is expected, but the error could be clearer), or `Endpoint Creators` (I think this should be enough for a plan to work, right?)

Does #60 fix this?

**Comment by xuzhang3** [comment]
@Console32  #60 won't fix this issue. I need to do some investigation.

**Comment by xuzhang3** [comment]
@Console32 What is error message when you role is under `project reader`?  ADO permission is based PAT. If you only want the read project permissions, you need add the `item` read permission too.

**Comment by raphaelschnaitl** [comment]
@xuzhang3 
If I am project reader, the terraform plan code fails with the nil panic in the OP on the exact same code line.

**Comment by xuzhang3** [comment]
Is this project in the same organization  your  PAT can manage? 
![image](https://user-images.githubusercontent.com/57888764/87661555-5ea1bf80-c793-11ea-98e3-d263e39cc0c2.png)

**Comment by raphaelschnaitl** [comment]
I did not create the PAT myself, It is the PAT which the agent uses to talk to azure devops:

Release Pipeline:
![image](https://user-images.githubusercontent.com/4870099/87668777-0657c700-c76d-11ea-828f-09496067a91f.png)

In YAML I do not change any setting. The System.AccessToken is set by default and can be used inside the yaml.

**Comment by xuzhang3** [comment]
Personal access token is used to grant the permissions to ADO provider. We don't use Oauth token.  
Can you provide the error logs? I cannot confirm if this is an ADO provide issue.

**Comment by raphaelschnaitl** [comment]
Sorry for the late response, the issue is related to the Personal Access Token that is provided by Azure Release Pipelines ($System.AccessToken). The issue originates from missing permissions. Probably you could extend the error handling to report the proper error. 

I created a Issue here. https://developercommunity.visualstudio.com/content/problem/1103505/azure-devops-release-pipeline-does-behave-differen.htm

The Release Pipeline does provide a different System.AccessToken than the YAML Pipeline does. The Release Pipeline is missing permissions, which causes the panic.

As described above, the error can be reproduced by creating a azuredevops_serviceendpoint_azurerm using Administrator permissions, removing those permissions (adding for example reader permissions) and running a terraform plan.
