### ISSUE TITLE
Error thrown when trying to create an Azure repo with a private repo import

### ISSUE THREAD

**Issue by scottenriquez** [microsoft/terraform-provider-azuredevops#439]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
Terraform v1.0.5
on darwin_amd64
provider registry.terraform.io/microsoft/azuredevops v0.1.6

### Affected Resource(s)

* `azuredevops_git_repository` (specifically private repo import)

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">=0.1.0"
    }
  }
}

resource "azuredevops_project" "project" {
  name        = "Project Name"
  description = "Project Description"
}

# copied directly from here: https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository
resource "azuredevops_git_repository" "repo" {
  project_id = azuredevops_project.project.id
  name       = "Sample Import an Existing Repository"
  initialization {
    init_type   = "Import"
    source_type = "Git"
    source_url  = "https://dev.azure.com/example-org/private-repository.git"
    username    = "example-org"
    password    = "<PAT>"
  }
}

```

### Debug Output

[Link to Gist](https://gist.github.com/scottenriquez/4c9857d7b26600f9ae5e7f02873c6cf2).

### Expected Behavior

Expected the provider to support arguments for username and password or access token so that a private repo can be imported.

### Actual Behavior

Error thrown while running `terraform plan`. See [Gist](https://gist.github.com/scottenriquez/4c9857d7b26600f9ae5e7f02873c6cf2) for output.

### Steps to Reproduce

1. Copy HCL above
2. Run `terraform init`
3. Run `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by xuzhang3** [comment]
Hi @scottenriquez Import private repository with `username` and  `password` is not supported by this provider. You should create a service connection first, then you can import the private repository with the service connection. The document error in https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/git_repository has been fixed but not released.
Example:
```
resource "azuredevops_serviceendpoint_generic_git" "serviceendpoint" {
  project_id            = azuredevops_project.project.id
  repository_url        = "https://dev.azure.com/org/project/_git/repository"
  username              = "username"
  password              = "<password>/<PAT>"
  service_endpoint_name = "Sample Generic Git"
  description           = "Managed by Terraform"
}

resource "azuredevops_git_repository" "repo" {
  project_id = azuredevops_project.project.id
  name       = "Sample Import an Existing Repository"
  initialization {
    init_type             = "Import"
    source_type           = "Git"
    source_url            = "https://dev.azure.com/example-org/private-repository.git"
    service_connection_id = azuredevops_serviceendpoint_generic_git.serviceendpoint.id
  }
}
```

**Comment by riccardoj** [comment]
Hi @xuzhang3 I have taken your example above but this failed again with a 400 error:

`Error: Error import repository in Azure DevOps: Request returned status: 400 Bad Request
  with azuredevops_git_repository.repo,`
`  on devops_project_setup.tf line 10, in resource "azuredevops_git_repository" "repo":`
`  10: resource "azuredevops_git_repository" "repo" {`

In the "azuredevops_serviceendpoint_generic_git" resource where the attribute is "repository_url" is this meant to be the source repository to import from?

My end goal is to import a Git repository from GitHub into an Azure DevOps Git repository.

TY

**Comment by scottenriquez** [comment]
@xuzhang3 thank you so much for the clarification! The HCL you provided works for me 👍🏼

**Comment by riccardoj** [comment]
> Hi @xuzhang3 I have taken your example above but this failed again with a 400 error:
> 
> `Error: Error import repository in Azure DevOps: Request returned status: 400 Bad Request with azuredevops_git_repository.repo,`
> ` on devops_project_setup.tf line 10, in resource "azuredevops_git_repository" "repo":`
> ` 10: resource "azuredevops_git_repository" "repo" {`
> 
> In the "azuredevops_serviceendpoint_generic_git" resource where the attribute is "repository_url" is this meant to be the source repository to import from?
> 
> My end goal is to import a Git repository from GitHub into an Azure DevOps Git repository.
> 
> TY

For anyone else facing a similar symptom to the one I explained, this was resolved by removing the "organisation" prefix from the Azure DevOps destination URL inside the service connection.

Working = https://dev.azure.com/org/project/_git/repository

NOT Working = https://org@dev.azure.com/org/project/_git/repository

**Comment by alex-3sr** [comment]
Hi all ;)

On my scenario where I want to import GIT between same DevOps organisation, I've still have the 400 Bad Request error :(

Here my part of code : 
```hcl
resource "azuredevops_git_repository" "repo" {
  for_each   = var.environment == "DEV" ? local.xxxx : {}
  project_id = data.azuredevops_project.devops_projects[each.value[0]].id
  name       = "${each.key}.Terraform"

  initialization {
    init_type   = "Import"
    source_type = "Git"
    source_url  = "https://dev.azure.com/DevopsOrgName/DevOpsProjectName/_git/GitRepoName"
    service_connection_id = azuredevops_serviceendpoint_generic_git.serviceendpoint_template[0].id
  }
  lifecycle {
    prevent_destroy = true
  }
}
resource "azuredevops_serviceendpoint_generic_git" "serviceendpoint_template" {
  count                 = var.environment == "DEV" ? 1 : 0
  project_id            = data.azuredevops_project.devops_projects["DevOpsProjectName"].id
  repository_url        = "https://dev.azure.com/DevopsOrgName/DevOpsProjectName/_git/GitRepoName"
  username              = "xxxx"
  password              = "yyyy"
  service_endpoint_name = "GIT-Template"
}
```

The goal here is just to have GIT template and permit to create new repo GIT in same DevOps with importing the template. I think the Bad Request error is linked to this issue based on differents comment that I can read here.

Thanks for your help
Regards
Alexandre

**Comment by xuzhang3** [comment]
@alex-3sr  what `password` used here?  The  `password` should be the  personal access token for devops repos.

**Comment by alex-3sr** [comment]
Hi @xuzhang3 , oh it's correct ! I used GIT password and it was not working, now swapping to PAT token and works like a charm ! Thank you
I think that documentation need to be updated for precise this information on this page https://registry.terraform.io/providers/microsoft/azuredevops/latest/docs/resources/serviceendpoint_generic_git

BTW, now it's working, thank you again
Regards
Alex

**Comment by xuzhang3** [comment]
close this issue, feel free to open  another if you still have questions.
